export const IDENTITY_SERVICE = 'IDENTITY_SERVICE';
export const CATALOG_SERVICE = 'CATALOG_SERVICE';
export const CRM_SERVICE = 'CRM_SERVICE';
export const INVENTORY_SERVICE = 'INVENTORY_SERVICE';
export const ORDERS_SERVICE = 'ORDERS_SERVICE';
